### ISSUE TITLE
用dubbo-go-samples的go-lient连接里面的java-server时候报错：Failed to check the status of the service org.apache.dubbo.UserProvider. No provider available for the service to the consumer use dubbo version 1.3.0

### ISSUE THREAD

**Issue by fumenglin** [apache/dubbo-go#1080]
Java的server和client之间可以相互通信，go的server和client之间可以相互通信；
用dubbo-go-samples的go-lient连接里面的java-server时候报错：Failed to check the status of the service org.apache.dubbo.UserProvider. No provider available for the service to the consumer use dubbo version 1.3.0

详细错误：
2021-03-09T18:13:13.766+0800    DEBUG   zookeeper/client.go:333 after zkClient{zk registry} unregister event{path:/dubbo/org.apache.dubbo.UserProvider/providers, event:0xc000238000}, array length 0
2021-03-09T18:13:13.771+0800    INFO    zookeeper/listener.go:227       listenDirEvent(path{/dubbo/org.apache.dubbo.UserProvider/providers}) = error{has none children}
2021-03-09T18:13:13.772+0800    DEBUG   zookeeper/client.go:312 zkClient{zk registry} register event{path:/dubbo/org.apache.dubbo.UserProvider/providers, ptr:0xc000238000}
2021-03-09T18:13:13.846+0800    ERROR   config/config_loader.go:155     Failed to check the status of the service org.apache.dubbo.UserProvider. No provider available for the service to the consumer use dubbo version 1.3.0
github.com/apache/dubbo-go/config.loadConsumerConfig
        /Users//goCode/pkg/mod/github.com/apache/dubbo-go@v1.5.5/config/config_loader.go:155
github.com/apache/dubbo-go/config.Load
        /Users/goCode/pkg/mod/github.com/apache/dubbo-go@v1.5.5/config/config_loader.go:324
main.main
        /Users//goCode/dubbo-go-samples/helloworld/go-client/cmd/client.go:50
runtime.main
        /usr/local/go/src/runtime/proc.go:204
panic: Failed to check the status of the service org.apache.dubbo.UserProvider. No provider available for the service to the consumer use dubbo version 1.3.0

goroutine 1 [running]:
github.com/apache/dubbo-go/config.loadConsumerConfig()
        /Users/goCode/pkg/mod/github.com/apache/dubbo-go@v1.5.5/config/config_loader.go:156 +0xc8d
github.com/apache/dubbo-go/config.Load()
        /Users/goCode/pkg/mod/github.com/apache/dubbo-go@v1.5.5/config/config_loader.go:324 +0x13a
main.main()
        /Users/goCode/dubbo-go-samples/helloworld/go-client/cmd/client.go:50 +0x4a
exit status 2

go.mod为：
go 1.15

require (
	github.com/apache/dubbo-go v1.5.5
	github.com/apache/dubbo-go-hessian2 v1.8.2
	github.com/apache/dubbo-go-samples v1.5.5-rc1
	github.com/dubbogo/gost v1.9.5
)

这里github.com/dubbogo/gost 有个问题，最新的v1.10.5没有gost/page；用v1.9.5的版本才可以。

代码样例没有做修改，就是自己启动了一个zk;
请问是不是版本的依赖的问题？

**Comment by fumenglin** [comment]
> Java的server和client之间可以相互通信，go的server和client之间可以相互通信；
> 用dubbo-go-samples的go-lient连接里面的java-server时候报错：Failed to check the status of the service org.apache.dubbo.UserProvider. No provider available for the service to the consumer use dubbo version 1.3.0
> 
> 详细错误：
> 2021-03-09T18:13:13.766+0800 DEBUG zookeeper/client.go:333 after zkClient{zk registry} unregister event{path:/dubbo/org.apache.dubbo.UserProvider/providers, event:0xc000238000}, array length 0
> 2021-03-09T18:13:13.771+0800 INFO zookeeper/listener.go:227 listenDirEvent(path{/dubbo/org.apache.dubbo.UserProvider/providers}) = error{has none children}
> 2021-03-09T18:13:13.772+0800 DEBUG zookeeper/client.go:312 zkClient{zk registry} register event{path:/dubbo/org.apache.dubbo.UserProvider/providers, ptr:0xc000238000}
> 2021-03-09T18:13:13.846+0800 ERROR config/config_loader.go:155 Failed to check the status of the service org.apache.dubbo.UserProvider. No provider available for the service to the consumer use dubbo version 1.3.0
> github.com/apache/dubbo-go/config.loadConsumerConfig
> /Users//goCode/pkg/mod/github.com/apache/dubbo-go@v1.5.5/config/config_loader.go:155
> github.com/apache/dubbo-go/config.Load
> /Users/goCode/pkg/mod/github.com/apache/dubbo-go@v1.5.5/config/config_loader.go:324
> main.main
> /Users//goCode/dubbo-go-samples/helloworld/go-client/cmd/client.go:50
> runtime.main
> /usr/local/go/src/runtime/proc.go:204
> panic: Failed to check the status of the service org.apache.dubbo.UserProvider. No provider available for the service to the consumer use dubbo version 1.3.0
> 
> goroutine 1 [running]:
> github.com/apache/dubbo-go/config.loadConsumerConfig()
> /Users/goCode/pkg/mod/github.com/apache/dubbo-go@v1.5.5/config/config_loader.go:156 +0xc8d
> github.com/apache/dubbo-go/config.Load()
> /Users/goCode/pkg/mod/github.com/apache/dubbo-go@v1.5.5/config/config_loader.go:324 +0x13a
> main.main()
> /Users/goCode/dubbo-go-samples/helloworld/go-client/cmd/client.go:50 +0x4a
> exit status 2
> 
> go.mod为：
> go 1.15
> 
> require (
> github.com/apache/dubbo-go v1.5.5
> github.com/apache/dubbo-go-hessian2 v1.8.2
> github.com/apache/dubbo-go-samples v1.5.5-rc1
> github.com/dubbogo/gost v1.9.5
> )
> 
> 这里github.com/dubbogo/gost 有个问题，最新的v1.10.5没有gost/page；用v1.9.5的版本才可以。
> 
> 代码样例没有做修改，就是自己启动了一个zk;
> 请问是不是版本的依赖的问题？
