### ISSUE TITLE
provider频繁上下线时，consumer端会panic

### ISSUE THREAD

**Issue by whitekeyboard** [apache/dubbo-go#1100]
注册中心为nacos，provider频繁上线时，consumer会出现以下异常：
```
panic: runtime error: invalid memory address or nil pointer dereference

[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x9edf17]


goroutine 278 [running]:

github.com/apache/dubbo-go/protocol/protocolwrapper.buildInvokerChain(0x0, 0x0, 0x103ff2f, 0x10, 0xc00020d000, 0xc000010201)

          src/github.com/apache/dubbo-go/protocol/protocolwrapper/protocol_filter_wrapper.go:71 +0x37

github.com/apache/dubbo-go/protocol/protocolwrapper.(*ProtocolFilterWrapper).Refer(0xc000436ed0, 0xc00016cd80, 0x1036eac, 0x6)

          src/github.com/apache/dubbo-go/protocol/protocolwrapper/protocol_filter_wrapper.go:62 +0x74

github.com/apache/dubbo-go/registry/directory.(*RegistryDirectory).cacheInvoker(0xc00016ca80, 0xc00016ccc0, 0x1c, 0xc000509b00)

          src/github.com/apache/dubbo-go/registry/directory/directory.go:299 +0x562

github.com/apache/dubbo-go/registry/directory.(*RegistryDirectory).cacheInvokerByEvent(0xc00016ca80, 0xc0005099e0, 0x1b, 0xc000509a80, 0x1, 0x1)

         src/github.com/apache/dubbo-go/registry/directory/directory.go:185 +0x11d

github.com/apache/dubbo-go/registry/directory.(*RegistryDirectory).refreshInvokers(0xc00016ca80, 0xc000308020, 0x1, 0x1)

         src/github.com/apache/dubbo-go/registry/directory/directory.go:133 +0x11a

created by github.com/apache/dubbo-go/registry/directory.(*RegistryDirectory).Notify

         src/github.com/apache/dubbo-go/registry/directory/directory.go:107 +0x5d
```

初步定位了一下：
```
// Notify monitor changes from registry,and update the cacheServices
func (dir *RegistryDirectory) Notify(event *registry.ServiceEvent) {
	if event == nil {
		return
	}
	go dir.refreshInvokers(event)
}
```
provider上下线时，此处是go协程处理，同一个interface的下线处理和上线处理可能并行处理invoker, 导致panic。

出现概率：偶现
版本：dubbo-go-v1.5.5

**Comment by whitekeyboard** [comment]
#1101 此问题和当前问题应该是同一个问题，只是panic位置不同

**Comment by whitekeyboard** [comment]
#1101 此问题和当前问题应该是同一个问题，只是panic位置不同

**Comment by whitekeyboard** [comment]
补充一下：
dubbo协议的Refer函数会返回nil，导致上述的panic
```
// Refer create dubbo service reference.
func (dp *DubboProtocol) Refer(url *common.URL) protocol.Invoker {
	exchangeClient := getExchangeClient(url)
	if exchangeClient == nil {
		logger.Warnf("can't dial the server: %+v", url.Location)
		return nil
	}
	invoker := NewDubboInvoker(url, exchangeClient)
	dp.SetInvokers(invoker)
	logger.Infof("Refer service: %s", url.String())
	return invoker
}
```

**Comment by whitekeyboard** [comment]
```
// Notify monitor changes from registry,and update the cacheServices
func (dir *RegistryDirectory) Notify(event *registry.ServiceEvent) {
	if event == nil {
		return
	}
	go dir.refreshInvokers(event)
}
```
此处的Notify函数直接启用协程处理，个人感觉不是太恰当，尤其对于同一地址和端口的同一interface，上线和下线是应该需要考虑时序的。

**Comment by AlexStocks** [comment]
pls check pr https://github.com/apache/dubbo-go/pull/1092

**Comment by jack15083** [comment]
> pls check pr #1092



> ```
> // Notify monitor changes from registry,and update the cacheServices
> func (dir *RegistryDirectory) Notify(event *registry.ServiceEvent) {
> 	if event == nil {
> 		return
> 	}
> 	go dir.refreshInvokers(event)
> }
> ```
> 
> 此处的Notify函数直接启用协程处理，个人感觉不是太恰当，尤其对于同一地址和端口的同一interface，上线和下线是应该需要考虑时序的。

这段代码可能是有问题的，有可能先执行的上线通知后执行的下线通知，这样的话就可能会导致consumer调用provider服务失败

**Comment by whitekeyboard** [comment]
@jack15083 是的，此处使用协程处理，可能导致两个问题，一个就是时序问题，另外一个就是操作同一资源导致崩溃的问题了。我当前遇到的就是崩溃的问题。当然时序问题肯定也是必须要考虑的。
