### ISSUE TITLE
Generic call does not work with 3.0 service discovery model

### ISSUE THREAD

**Issue by chickenlj** [apache/dubbo-go#2034]
```text
2022-08-26T09:19:18.080Z	WARN	proxy/proxy.go:211	[CallProxy] received rpc err: Failed to invoke the method $invoke. No provider available for the service dubbo://:@:/?interface=org.apache.dubbo.samples.UserProvider&group=&version= from registry service-discovery-registry://127.0.0.1:2181?registry=zookeeper&registry.group=&registry.label=true&registry.namespace=&registry.preferred=false&registry.role=0&registry.timeout=5s&registry.ttl=10s&registry.weight=0&registry.zone=&remote-client-name=dubbo.registries-zookeeper-127.0.0.1%3A2181&simplified=false on the consumer 10.1.0.61 using the dubbo version 3.0.0 .Please check if the providers have been started and registered.
    userprovider_test.go:41: 
        	Error Trace:	/home/runner/work/dubbo-go/dubbo-go/samples/integrate_test/generic/default/tests/integration/userprovider_test.go:41
        	Error:      	Expected nil, but got: Failed to invoke the method $invoke. No provider available for the service dubbo://:@:/?interface=org.apache.dubbo.samples.UserProvider&group=&version= from registry service-discovery-registry://127.0.0.1:2181?registry=zookeeper&registry.group=&registry.label=true&registry.namespace=&registry.preferred=false&registry.role=0&registry.timeout=5s&registry.ttl=10s&registry.weight=0&registry.zone=&remote-client-name=dubbo.registries-zookeeper-127.0.0.1%3A2181&simplified=false on the consumer 10.1.0.61 using the dubbo version 3.0.0 .Please check if the providers have been started and registered.
        	Test:       	TestGetUser1
    userprovider_test.go:42: 
        	Error Trace:	/home/runner/work/dubbo-go/dubbo-go/samples/integrate_test/generic/default/tests/integration/userprovider_test.go:42
        	Error:      	Object expected to be of type map[interface {}]interface {}, but was <nil>
        	Test:       	TestGetUser1
--- FAIL: TestGetUser1 (0.00s)
panic: interface conversion: interface {} is nil, not map[interface {}]interface {} [recovered]
	panic: interface conversion: interface {} is nil, not map[interface {}]interface {}

goroutine 26 [running]:
testing.tRunner.func1.1(0x1aa3580, 0xc00057b920)
	/opt/hostedtoolcache/go/1.15.15/x64/src/testing/testing.go:1072 +0x30d
testing.tRunner.func1(0xc0007e5b00)
	/opt/hostedtoolcache/go/1.15.15/x64/src/testing/testing.go:1075 +0x41a
panic(0x1aa3580, 0xc00057b920)
	/opt/hostedtoolcache/go/1.15.15/x64/src/runtime/panic.go:969 +0x1b9
github.com/apache/dubbo-go-samples/integrate_test/generic/default/tests/integration.TestGetUser1(0xc0007e5b00)
	/home/runner/work/dubbo-go/dubbo-go/samples/integrate_test/generic/default/tests/integration/userprovider_test.go:43 +0x89f
testing.tRunner(0xc0007e5b00, 0x1e68058)
	/opt/hostedtoolcache/go/1.15.15/x64/src/testing/testing.go:1123 +0xef
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.15.15/x64/src/testing/testing.go:1168 +0x2b3
FAIL	github.com/apache/dubbo-go-samples/integrate_test/generic/default/tests/integration	0.051s
FAIL
make: *** [build/Makefile:161: integration] Error 1
>  print server log with /home/runner/work/dubbo-go/dubbo-go/samples/generic/default/go-server/dist/linux_amd64/release/default.log
enp3s0: error fetching interface information: Device not found
2022-08-26T09:19:09.249Z	INFO	config/config_loader_options.go:201	The following profiles are active: default
2022-08-26T09:19:09.251Z	INFO	config/root_config.go:130	[Config Center] Config center doesn't start
2022/08/26 09:19:09 Connected to 127.0.0.1:2181
2022-08-26T09:19:09.254Z	WARN	config/provider_config.go:167	Dubbogo can not find service with registeredTypeName User in configuration. Use the default configuration instead.
2022-08-26T09:19:09.254Z	ERROR	config/provider_config.go:171	Dubbogo do not read service interface name with registeredTypeName = User.Please run go install github.com/dubbogo/tools/cmd/protoc-gen-go-triple@latest to update your protoc-gen-go-triple and re-generate your pb file again.If you are not using pb serialization, please set 'interface' field in service config.
dubbo.apache.org/dubbo-go/v3/config.(*ProviderConfig).Load
	/home/runner/go/pkg/mod/github.com/chickenlj/dubbo-go/v3@v3.0.0-20220826050830-69d164d982d9/config/provider_config.go:171
dubbo.apache.org/dubbo-go/v3/config.(*RootConfig).Start.func1
	/home/runner/go/pkg/mod/github.com/chickenlj/dubbo-go/v3@v3.0.0-20220826050830-69d164d982d9/config/root_config.go:205
sync.(*Once).doSlow
	/opt/hostedtoolcache/go/1.15.15/x64/src/sync/once.go:66
sync.(*Once).Do
	/opt/hostedtoolcache/go/1.15.15/x64/src/sync/once.go:57
dubbo.apache.org/dubbo-go/v3/config.(*RootConfig).Start
	/home/runner/go/pkg/mod/github.com/chickenlj/dubbo-go/v3@v3.0.0-20220826050830-69d164d982d9/config/root_config.go:202
dubbo.apache.org/dubbo-go/v3/config.(*RootConfig).Init
	/home/runner/go/pkg/mod/github.com/chickenlj/dubbo-go/v3@v3.0.0-20220826050830-69d164d982d9/config/root_config.go:197
dubbo.apache.org/dubbo-go/v3/config.Load
	/home/runner/go/pkg/mod/github.com/chickenlj/dubbo-go/v3@v3.0.0-20220826050830-69d164d982d9/config/config_loader.go:59
main.main
	/home/runner/work/dubbo-go/dubbo-go/samples/generic/default/go-server/cmd/server.go:45
runtime.main
	/opt/hostedtoolcache/go/1.15.15/x64/src/runtime/proc.go:204
```

**Comment by zhaoyunxing92** [comment]
有可以复现的代码吗

**Comment by pengjiaxin** [comment]
朋友，您的邮件我已收到，我将以超光速回复您。

**Comment by Lvnszn** [comment]
我这边复现不出来。 在我启动 go server 之后，在执行 samples 里面的 test 都是 passed
<img width="1087" alt="image" src="https://user-images.githubusercontent.com/12541438/193186191-b65988a6-9c1d-4bab-9670-13316985de7a.png">

<img width="1389" alt="image" src="https://user-images.githubusercontent.com/12541438/193186248-25c55385-48f4-4585-806f-02223830bb78.png">

**Comment by Lvnszn** [comment]
https://github.com/apache/dubbo-go-samples/blob/master/integrate_test/generic/default/tests/integration/userprovider_test.go 

测试代码

**Comment by Lvnszn** [comment]
复现出来了，上次写错配置了

**Comment by Lvnszn** [comment]
应用级 + 泛化调用 + local meta 模式会报错，获取不到接口。需要云兴佬哥帮忙确认一下是不是没有实现获取本地接口的逻辑。我这边看代码是没有实现。
remote 模式因为 zk 有个 bug，会连不上 zk，等那个 bug 修复在看看 remote 模式是不是 ok 的。
