### ISSUE TITLE
dubbo-3.1.0 nacos配置中心获取不到配置

### ISSUE THREAD

**Issue by leapig** [apache/dubbo-go#2365]
- Server: Dubbo-go, v3.1.0
- Client: Dubbo-go, v3.1.0
- Protocol: Triple
- Registry: Nacos, v2.1.0

### Issue description

dubbo-go由3.0.5升级到3.1.0后nacos配置中心获取不到配置，大概率应该是升级[nacos-sdk-go](https://github.com/nacos-group/nacos-sdk-go)到V2导致的

### Logs

<details><summary>报错日志</summary>

```
2023-07-28 10:05:55	INFO	logger/logging.go:42	The following profiles are active: [default]
2023-07-28 10:05:55	INFO	nacos/impl.go:78	[Nacos ConfigCenter] New Nacos ConfigCenter with Configuration: &{BaseDynamicConfiguration:{} url:0xc0009ee540 rootPath: wg:{noCopy:{} state1:[0 0 0]} cltLock:{state:0 sema:0} done:0xc00047e660 client:<nil> keyListeners:{mu:{state:0 sema:0} read:{v:<nil>} dirty:map[] misses:0} parser:<nil>}, url = nacos://nacos:B4236BB549953C176552966406EDFC2E308BAC57@nacos:8848?config-center.appId=dubbo&config-center.cluster=&config-center.group=&config-center.namespace=&config-center.timeout=10s&nacos.access=&nacos.group=DEFAULT_GROUP&nacos.namespaceId=&nacos.password=B4236BB549953C176552966406EDFC2E308BAC57&nacos.secret=&nacos.timeout=10s&nacos.username=nacos&remote-client-name=dubbo.config-center-nacos-nacos%3A8848
2023-07-28T10:05:55.437+0800	INFO	nacos_client/nacos_client.go:65	logDir:</app/log> cacheDir:</app/cache>
2023-07-28 10:06:04	WARN	config/config_center_config.go:146	[Config Center] Dynamic config center has started, but config may not be initialized, because: read config from both server and cache fail, err=failed to read config cache file:/app/cache/config/client@@DEFAULT_GROUP@@, cacheDir:/app/cache/config, err:open /app/cache/config/client@@DEFAULT_GROUP@@: no such file or directory ，dataId=client, group=DEFAULT_GROUP, namespaceId=
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
dubbo.apache.org/dubbo-go/v3/config.(*ReferenceConfig).Refer(0xc0005ec1a0, {0x1d853a0, 0xc000ccc000})
	/go/pkg/mod/dubbo.apache.org/dubbo-go/v3@v3.1.0/config/reference_config.go:276 +0xc45
dubbo.apache.org/dubbo-go/v3/config.(*ConsumerConfig).Load(0xc0000ec580)
	/go/pkg/mod/dubbo.apache.org/dubbo-go/v3@v3.1.0/config/consumer_config.go:146 +0x272
dubbo.apache.org/dubbo-go/v3/config.(*RootConfig).Start.func1()
	/go/pkg/mod/dubbo.apache.org/dubbo-go/v3@v3.1.0/config/root_config.go:211 +0x36
sync.(*Once).doSlow(0x40f4e7, 0xa8)
	/usr/local/go/src/sync/once.go:68 +0xd2
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:59
dubbo.apache.org/dubbo-go/v3/config.(*RootConfig).Start(0x1f05000)
	/go/pkg/mod/dubbo.apache.org/dubbo-go/v3@v3.1.0/config/root_config.go:209 +0x46
dubbo.apache.org/dubbo-go/v3/config.(*RootConfig).Init(0xc0000ec630)
	/go/pkg/mod/dubbo.apache.org/dubbo-go/v3@v3.1.0/config/root_config.go:204 +0x565
dubbo.apache.org/dubbo-go/v3/config.Load({0x0, 0xc000c60680, 0x7ff213af5cc8})
	/go/pkg/mod/dubbo.apache.org/dubbo-go/v3@v3.1.0/config/config_loader.go:65 +0xaa
main.main()
	/builds/fky/client/server/App.go:34 +0xc5
```

</details>

**Comment by justxuewei** [comment]
This issue is assigned to @binbin0325.

**Comment by leapig** [comment]
![image](https://github.com/apache/dubbo-go/assets/92301116/e4235a12-705a-4485-9709-449f3a9bc3a2)
nacos client已经实例化，没看到有相关执行拉配置的操作

**Comment by binbin0325** [comment]
看下nacos中是否有错误日志 ，在/app/log目录中

**Comment by leapig** [comment]
[nacos-sdk.log](https://github.com/apache/dubbo-go/files/12195284/nacos-sdk.log)

**Comment by leapig** [comment]
<img width="1364" alt="截屏2023-07-28 23 01 14" src="https://github.com/apache/dubbo-go/assets/92301116/7ef3cc2a-776a-4b10-a2d6-b8f1673467e5">
开启9848端口后依然无法无感升级，启动的服务和之前有明显区别，且启动第二个就会失败，服务称变dubbo.io的原因？provider和consumer都不见了

**Comment by leapig** [comment]
> 看下nacos中是否有错误日志 ，在/app/log目录中

能否给一份3.1.0的完整dubbo.yaml配置文件呢，感觉和3.0.5还是存在变动

**Comment by binbin0325** [comment]
配置没有变化，就是需要开通9848， 看看开通后日志是否还有报错？

**Comment by justxuewei** [comment]
@leapig Are you using interface-level service discovery? If yes, trying to add `registry-type: interface` to your config.

<img width="714" alt="image" src="https://github.com/apache/dubbo-go/assets/13026316/7297e729-5493-4c3a-88cf-101e5dcabc28">

**Comment by leapig** [comment]
> registry-type: interface

go 1.21
dubbo-go 3.1.0
nacos 2.1.0

加入这个配置就可以正常跑了

**Comment by yanhuilin** [comment]
registry-type: interface
请问这个配置加在哪里呢
