### ISSUE TITLE
有一个panic导致应用挂了

### ISSUE THREAD

**Issue by alan2016llg** [apache/dubbo-go#2650]
### Environment

- Server: java-dubbo
- Client: Dubbo-go, v3.1.1-rc
- Protocol: dubbo
- Registry: zk

### Issue description
应用挂了，查询docker最后日志，有一个panic出现，日志如下

### Logs

<details><summary>Click me to check logs</summary>

```
2024-04-02 10:25:39     INFO    getty/listener.go:90    session{session session-closed, Read Bytes: 21708, Write Bytes: 1248, Read Pkgs: 4, Write Pkgs: 4} is closing......
2024-04-02 10:25:39     INFO    getty/pool.go:221       after remove session{session session-closed, Read Bytes: 21708, Write Bytes: 1248, Read Pkgs: 4, Write Pkgs: 4}, left session number:0
2024-04-02 10:25:39     WARN    dubbo/dubbo_protocol.go:94      can't dial the server: 192.168.50.49:17624
2024-04-02 10:25:39     WARN    dubbo/dubbo_protocol.go:94      can't dial the server: 192.168.50.49:17624
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x166ded4]

goroutine 132598 [running]:
dubbo.apache.org/dubbo-go/v3/metadata/service/local.(*MetadataServiceProxy).GetMetadataInfo(0xc0018c4320, {0xc0018f4460?, 0xc00049c0a0?})
        /home/zmn/go/pkg/mod/dubbo.apache.org/dubbo-go/v3@v3.1.1-rc1/metadata/service/local/service_proxy.go:183 +0x394
dubbo.apache.org/dubbo-go/v3/registry/servicediscovery.GetMetadataInfo({0xc001d47b90?, 0x1e09060?}, {0x27803a0, 0xc00049c0a0}, {0xc0018f4460, 0x20})
        /home/zmn/go/pkg/mod/dubbo.apache.org/dubbo-go/v3@v3.1.1-rc1/registry/servicediscovery/service_instances_changed_listener_impl.go:257 +0x2a5
dubbo.apache.org/dubbo-go/v3/registry/servicediscovery.(*ServiceInstancesChangedListenerImpl).OnEvent(0xc001948100, {0x27671c0?, 0xc001211db0})
        /home/zmn/go/pkg/mod/dubbo.apache.org/dubbo-go/v3@v3.1.1-rc1/registry/servicediscovery/service_instances_changed_listener_impl.go:125 +0x8bf
dubbo.apache.org/dubbo-go/v3/registry/zookeeper.(*zookeeperServiceDiscovery).DataChange(0xc0004a39d0, {{0xc003e0b9c0, 0x38}, 0x0, {0xc0014ca700, 0x30b}})
        /home/zmn/go/pkg/mod/dubbo.apache.org/dubbo-go/v3@v3.1.1-rc1/registry/zookeeper/service_discovery.go:282 +0x303
dubbo.apache.org/dubbo-go/v3/remoting/zookeeper.(*ZkEventListener).listenDirEvent(0xc0024aae10, 0x0, {0xc000484660, 0x24}, {0x27491c0, 0xc0004a39d0}, {0x0, 0x0})
        /home/zmn/go/pkg/mod/dubbo.apache.org/dubbo-go/v3@v3.1.1-rc1/remoting/zookeeper/listener.go:406 +0xb7a
dubbo.apache.org/dubbo-go/v3/remoting/zookeeper.(*ZkEventListener).ListenServiceEvent.func1({0xc000484660, 0x24}, {0x27491c0?, 0xc0004a39d0?})
        /home/zmn/go/pkg/mod/dubbo.apache.org/dubbo-go/v3@v3.1.1-rc1/remoting/zookeeper/listener.go:480 +0xb1
created by dubbo.apache.org/dubbo-go/v3/remoting/zookeeper.(*ZkEventListener).ListenServiceEvent in goroutine 132645
        /home/zmn/go/pkg/mod/dubbo.apache.org/dubbo-go/v3@v3.1.1-rc1/remoting/zookeeper/listener.go:475 +0x17c
```

</details>

**Comment by chickenlj** [comment]
是纯dubbo-go应用，还是dubbo-go和dubbo-java互通的场景？

**Comment by FoghostCn** [comment]
When obtaining remote metadata, the ip address (192.168.50.49:17624) cannot be connected. Can you confirm that 192.168.50.49:17624 can be connected?

**Comment by alan2016llg** [comment]
通过泛化调用，dubbo-go调用java的dubbo服务。 @chickenlj

**Comment by alan2016llg** [comment]
现在无法确认当时是不是真的连不上了，可能当时网络有问题导致 @FoghostCn

**Comment by FoghostCn** [comment]
> 现在无法确认当时是不是真的连不上了，可能当时网络有问题导致 @FoghostCn

OK,我修复了一下这个问题，当链接不上服务端的时候日志报错而不是 panic 掉
